services:
  - type: web
    name: pentamark-frontend
    runtime: node
    plan: free
    rootDir: diffmark-frontend
    buildCommand: npm install && npm run build
    startCommand: npm run start -- --hostname 0.0.0.0 --port $PORT
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://pentamark-backend.onrender.com/api

  - type: web
    name: pentamark-backend
    runtime: python
    plan: free
    rootDir: DiffMark-main/webapp
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: PORT=$PORT python app.py
    envVars:
      - key: PORT
        value: 10000
      - key: FLASK_ENV
        value: production
      - key: MONGO_URI
        value: mongodb://localhost:27017
